#!/usr/bin/env node
/*
 * build-us-map.mjs — generates content/usMapGenerated.ts, the journey's atlas.
 *
 * Source: us-atlas states-albers-10m.json (US Census cartographic boundaries,
 * already projected with d3's geoAlbersUsa().scale(1300).translate([487.5, 305])
 * into a 975 x 610 frame). Alaska, Hawaii, and Puerto Rico are dropped: the
 * route runs San Diego → Los Angeles → San Francisco → New York, and the lower
 * 48 is the map that reads at a glance. The topology is simplified so the SVG
 * path ships at a fraction of the source size while every state edge survives.
 *
 * Places are projected with the identical projection so pins land on the real
 * cities. Re-run after changing journeyPlaces:
 *   node scripts/build-us-map.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { geoAlbersUsa, geoPath } from 'd3-geo';
import { mesh, merge } from 'topojson-client';
import { presimplify, quantile, simplify } from 'topojson-simplify';

const require = createRequire(import.meta.url);
const source = JSON.parse(
  readFileSync(require.resolve('us-atlas/states-albers-10m.json'), 'utf8'),
);

const EXCLUDED = new Set(['02', '15', '72']);
const WIDTH = 975;
const HEIGHT = 610;

/* Keep the strongest ~12% of vertices: coastlines stay recognisable, the
 * Great Lakes keep their shape, and the path text drops ~6x. */
const weighted = presimplify(source);
const topology = simplify(weighted, quantile(weighted, 0.88));
const states = topology.objects.states;
states.geometries = states.geometries.filter((g) => !EXCLUDED.has(g.id));

const projection = geoAlbersUsa()
  .scale(1300)
  .translate([WIDTH / 2, HEIGHT / 2]);
const path = geoPath(null).digits(1);

const nation = path(merge(topology, states.geometries));
const borders = path(mesh(topology, states, (a, b) => a !== b));

/* Real places, WGS84. The horizon is open Atlantic east of New York — the
 * unprinted margin the story ends in. */
const places = {
  'san-diego': { name: 'San Diego', lat: 32.7157, lng: -117.1611 },
  ucla: { name: 'Los Angeles', lat: 34.0689, lng: -118.4452 },
  'san-francisco': { name: 'San Francisco', lat: 37.7749, lng: -122.4194 },
  'new-york': { name: 'New York', lat: 40.7128, lng: -74.006 },
  horizon: { name: 'Horizon', lat: 39.4, lng: -66.5 },
};

const projected = Object.fromEntries(
  Object.entries(places).map(([id, place]) => {
    const point = projection([place.lng, place.lat]);
    if (!point) throw new Error(`${id} fell outside the projection`);
    return [
      id,
      {
        name: place.name,
        lat: place.lat,
        lng: place.lng,
        x: Number(point[0].toFixed(1)),
        y: Number(point[1].toFixed(1)),
      },
    ];
  }),
);

const banner = `/* Generated by scripts/build-us-map.mjs — do not edit by hand. */`;
const out = `${banner}

/** Frame the atlas paths are drawn in (d3 albersUsa at scale 1300). */
export const usMapWidth = ${WIDTH};
export const usMapHeight = ${HEIGHT};

/** Lower-48 outline, one path: the coast and both land borders. */
export const usNationPath = ${JSON.stringify(nation)};

/** Interior state borders only, so the coast is never drawn twice. */
export const usStateBordersPath = ${JSON.stringify(borders)};

export type UsPlaceId = ${Object.keys(places)
  .map((id) => `'${id}'`)
  .join(' | ')};

export type UsPlace = {
  name: string;
  lat: number;
  lng: number;
  /** Projected into the same frame as the paths above. */
  x: number;
  y: number;
};

export const usPlaces: Record<UsPlaceId, UsPlace> = ${JSON.stringify(projected, null, 2)};
`;

writeFileSync(new URL('../content/usMapGenerated.ts', import.meta.url), out);
console.log(
  `wrote content/usMapGenerated.ts: nation ${nation.length} chars, borders ${borders.length} chars`,
);
