import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const updater = await readFile(
  new URL('./update-history.mjs', import.meta.url),
  'utf8',
);

test('generated history copy stays plain and deterministic', () => {
  assert.match(
    updater,
    /description: `Auto-generated from commit \$\{head\.commit\}\.`/,
  );
  assert.doesNotMatch(updater, /description: `[^`]*—/);
  assert.match(
    updater,
    /Generated by scripts\/update-history\.mjs\. Do not edit this file\. Curated eras are defined in components\/concept\/conceptData\.ts\./,
  );
});
